const axios = require("axios");

async function addUser(params) {
  const data = [
    {
      niup: "12120014277",
      username: "hildah",
      password: "hildah123",
      passwordConfirmation: "hildah123",
      role: "wilayah",
      hp: "0",
    },
    {
      niup: "11920009246",
      username: "afidah",
      password: "afidah123",
      passwordConfirmation: "afidah123",
      role: "wilayah",
      hp: "0",
    },
    {
      niup: "11320406731",
      username: "dinda",
      password: "dinda123",
      passwordConfirmation: "dinda123",
      role: "wilayah",
      hp: "0",
    },
    {
      niup: "11620603287",
      username: "fitriyah",
      password: "fitriyah123",
      passwordConfirmation: "fitriyah123",
      role: "wilayah",
      hp: "0",
    },
    {
      niup: "11520201687",
      username: "himma",
      password: "himma123",
      passwordConfirmation: "himma123",
      role: "wilayah",
      hp: "0",
    },
    {
      niup: "11220404303",
      username: "fina",
      password: "fina123",
      passwordConfirmation: "fina123",
      role: "wilayah",
      hp: "0",
    },
    {
      niup: "12220216155",
      username: "hikmah",
      password: "hikmah123",
      passwordConfirmation: "hikmah123",
      role: "wilayah",
      hp: "0",
    },
    {
      niup: "11620403249",
      username: "jannah",
      password: "jannah123",
      passwordConfirmation: "jannah123",
      role: "wilayah",
      hp: "0",
    },
    {
      niup: "11920409258",
      username: "mellaty",
      password: "mellaty123",
      passwordConfirmation: "mellaty123",
      role: "daerah",
      hp: "0",
    },
    {
      niup: "11920008682",
      username: "vina",
      password: "vina123",
      passwordConfirmation: "vina123",
      role: "daerah",
      hp: "0",
    },
    {
      niup: "12220416689",
      username: "nada",
      password: "nada123",
      passwordConfirmation: "nada123",
      role: "daerah",
      hp: "0",
    },
    {
      niup: "12220616222",
      username: "mustifa",
      password: "mustifa123",
      passwordConfirmation: "mustifa123",
      role: "daerah",
      hp: "0",
    },
    {
      niup: "11620204531",
      username: "risma",
      password: "risma123",
      passwordConfirmation: "risma123",
      role: "daerah",
      hp: "0",
    },
    {
      niup: "11920808197",
      username: "atika",
      password: "atika123",
      passwordConfirmation: "atika123",
      role: "daerah",
      hp: "0",
    },
    {
      niup: "12220016651",
      username: "fajriyah",
      password: "fajriyah123",
      passwordConfirmation: "fajriyah123",
      role: "daerah",
      hp: "0",
    },
    {
      niup: "11620403075",
      username: "nadiya",
      password: "nadiya123",
      passwordConfirmation: "nadiya123",
      role: "daerah",
      hp: "0",
    },
    {
      niup: "12220216805",
      username: "wirda",
      password: "wirda123",
      passwordConfirmation: "wirda123",
      role: "daerah",
      hp: "0",
    },
    {
      niup: "12320416935",
      username: "ameliya",
      password: "ameliya123",
      passwordConfirmation: "ameliya123",
      role: "daerah",
      hp: "0",
    },
    {
      niup: "12220216752",
      username: "devita",
      password: "devita123",
      passwordConfirmation: "devita123",
      role: "daerah",
      hp: "0",
    },
    {
      niup: "12220016712",
      username: "qonita",
      password: "qonita123",
      passwordConfirmation: "qonita123",
      role: "daerah",
      hp: "0",
    },
    {
      niup: "12220016836",
      username: "husna",
      password: "husna123",
      passwordConfirmation: "husna123",
      role: "daerah",
      hp: "0",
    },
    {
      niup: "11920609691",
      username: "adinda",
      password: "adinda123",
      passwordConfirmation: "adinda123",
      role: "daerah",
      hp: "0",
    },
    {
      niup: "12220016135",
      username: "karroma",
      password: "karroma123",
      passwordConfirmation: "karroma123",
      role: "daerah",
      hp: "0",
    },
    {
      niup: "12220216069",
      username: "nilu",
      password: "nilu123",
      passwordConfirmation: "nilu123",
      role: "daerah",
      hp: "0",
    },
    {
      niup: "11620003096",
      username: "imania",
      password: "imania123",
      passwordConfirmation: "imania123",
      role: "daerah",
      hp: "0",
    },
    {
      niup: "12220216765",
      username: "riyana",
      password: "riyana123",
      passwordConfirmation: "riyana123",
      role: "daerah",
      hp: "0",
    },
    {
      niup: "21620802665",
      username: "nafilah",
      password: "nafilah123",
      passwordConfirmation: "nafilah123",
      role: "daerah",
      hp: "0",
    },
    {
      niup: "12220616439",
      username: "farida",
      password: "farida123",
      passwordConfirmation: "farida123",
      role: "daerah",
      hp: "0",
    },
    {
      niup: "11620003104",
      username: "aida",
      password: "aida123",
      passwordConfirmation: "aida123",
      role: "daerah",
      hp: "0",
    },
    {
      niup: "12220016911",
      username: "arini",
      password: "arini123",
      passwordConfirmation: "arini123",
      role: "daerah",
      hp: "0",
    },
    {
      niup: "11820600621",
      username: "naimah",
      password: "naimah123",
      passwordConfirmation: "naimah123",
      role: "daerah",
      hp: "0",
    },
    {
      niup: "12220416143",
      username: "zamiya",
      password: "zamiya123",
      passwordConfirmation: "zamiya123",
      role: "daerah",
      hp: "0",
    },
    {
      niup: "12220216828",
      username: "rizqiyanti",
      password: "rizqiyanti123",
      passwordConfirmation: "rizqiyanti123",
      role: "daerah",
      hp: "0",
    },
    {
      niup: "12220216430",
      username: "wafiqah",
      password: "wafiqah123",
      passwordConfirmation: "wafiqah123",
      role: "daerah",
      hp: "0",
    },
    {
      niup: "11920409659",
      username: "nuva",
      password: "nuva123",
      passwordConfirmation: "nuva123",
      role: "daerah",
      hp: "0",
    },
    {
      niup: "11620604180",
      username: "nadifa",
      password: "nadifa123",
      passwordConfirmation: "nadifa123",
      role: "daerah",
      hp: "0",
    },
    {
      niup: "11920810210",
      username: "novita",
      password: "novita123",
      passwordConfirmation: "novita123",
      role: "wilayah",
      hp: "0",
    },
    {
      niup: "11320803421",
      username: "merysca",
      password: "merysca123",
      passwordConfirmation: "merysca123",
      role: "wilayah",
      hp: "0",
    },
    {
      niup: "11920810227",
      username: "zaheoil",
      password: "zaheoil123",
      passwordConfirmation: "zaheoil123",
      role: "wilayah",
      hp: "0",
    },
    {
      niup: "11520400894",
      username: "hilya",
      password: "hilya123",
      passwordConfirmation: "hilya123",
      role: "wilayah",
      hp: "0",
    },
    {
      niup: "11820800905",
      username: "sholihah",
      password: "sholihah123",
      passwordConfirmation: "sholihah123",
      role: "wilayah",
      hp: "0",
    },
  ];

  try {
    const requests = data.map((user) =>
      axios.post("https://api-puber.nuruljadid.net/api/v2/user", user, {
        headers: {
          "x-auth":
            "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InV1aWQiOiI4Y2RjMTU5Yi00ZDg3LTExZWYtYTFjNC1iODZiMjM1YzgwMTQiLCJuYW1hX2xlbmdrYXAiOiJTZXB0aWEgUW9ycmkgJ2FpbmEiLCJuaXVwIjoxMTQyMDIwNDEzOSwiamVuaXNfa2VsYW1pbiI6IlAiLCJpZF9ibG9rIjpudWxsLCJibG9rIjpudWxsLCJhbGlhc193aWxheWFoIjpudWxsLCJ3aWxheWFoIjpudWxsLCJ1c2VybmFtZSI6InNlcHRpYXEiLCJwYXNzd29yZCI6bnVsbCwiaHAiOm51bGwsInJvbGUiOiJzeXNhZG1pbiIsImNyZWF0ZWRBdCI6IjIwMjQtMDctMjlUMDg6NDg6MDcuMDAwWiIsInVwZGF0ZWRBdCI6IjIwMjQtMDctMjlUMDg6NDg6MDcuMDAwWiJ9LCJpYXQiOjE3NDA1NDA2NzMsImV4cCI6MTc0MDU4Mzg3M30.MJrqnrycDQP9EiCYGpktG4ZtP2FybSslStIarYebV4o",
        },
      })
    );

    const responses = await Promise.all(requests);
    responses.forEach((resp) => console.log(resp.data));
  } catch (err) {
    console.log(err?.response?.data ?? err.message);
  }
}

addUser();
