name: Development API

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          
      - name: SSH to Server DEV
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_SERVER_HOST }}
          username: ${{ secrets.PROD_SERVER_USERNAME }}
          password: ${{ secrets.PROD_SERVER_PASSWORD }}
          source: "dist/"
          target: "/var/www/html/pubernj"
          port: ${{ secrets.PROD_SERVER_PORT }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd /home/pubernj/pubernj-v2-be/
            pm2 stop 1
            git checkout dev
            git pull
            npm install
            export PATH=$PATH:/home/pubernj/.nvm/versions/node/v18.20.4/bin
            npx sequelize db:migrate
            pm2 start 1
