name: Development API

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH to Server DEV
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_SERVER_HOST }}
          username: ${{ secrets.PROD_SERVER_USERNAME }}
          password: ${{ secrets.PROD_SERVER_PASSWORD }}
          source: "dist/"
          target: "/var/www/html/pubernj"
          port: ${{ secrets.PROD_SERVER_PORT }}
          script: |
            cd /home/pubernj/pubernj-v2-be/
            pm2 stop 1
            git checkout dev
            git pull
            npm install
            npx sequelize-cli db:migrate
            pm2 start 1
